tasks:
  - name: httpie
    command: pip install httpie

  - name: siege
    command: >
      sudo apt-get install siege &&
      siege -V
  - name: netstat
    command: >
      sudo apt update &&
      sudo apt install net-tools
  - name: java
    command: >
      sdk install java 17.0.3-ms < /dev/null &&
      sdk default java 17.0.3-ms &&
      java --version &&
      gp sync-done init-java
  - name: kafka-docker
    command: > 
      cd kafka-docker &&
      docker-compose up -d
  - name: kafka-zookeeper
    init: gp sync-await init-java
    command: >
      cd /usr/local &&
      sudo wget https://dlcdn.apache.org/kafka/3.2.0/kafka_2.13-3.2.0.tgz &&
      sudo tar xzf kafka_2.13-3.2.0.tgz &&
      sudo mv kafka_2.13-3.2.0 /usr/local/kafka &&
      gp sync-done init-kafka-zookeeper &&
      sudo chmod -R 777 kafka &&
      /usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
  - name: kafka-server 
    init: gp sync-await init-kafka-zookeeper
    command: > 
      cd /usr/local &&
      sudo chmod -R 777 kafka &&
      /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties &&
      gp sync-done init-kafka-server
  - name: kubectl
    command: >
      curl -LO https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl &&
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&
      kubectl version --client &&
      gp sync-done init-kubectl
  - name: python
    init: gp sync-await init-kubectl
    command: >
      sudo apt install python-is-python3 &&
      gp sync-done init-python
  - name: awscli
    init: gp sync-await init-python
    command: >
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
      unzip -o awscliv2.zip &&
      sudo ./aws/install &&
      gp sync-done init-awscli
  - name: eksctl
    init: gp sync-await init-awscli
    command: >
      curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp &&
      sudo mv /tmp/eksctl /usr/local/bin &&
      eksctl version &&
      gp sync-done init-eksctl
  - name: boot
    init: gp sync-await init-eksctl
    command: >
      cat ./config/init
  - name: helm
    command: >
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 &&
      chmod 700 get_helm.sh &&
      ./get_helm.sh
  - name: aws-iam-authenticator
    command: >
      curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/aws-iam-authenticator &&
      chmod +x ./aws-iam-authenticator &&
      sudo cp ./aws-iam-authenticator /usr/local/bin/
vscode:
  extensions:
    - redhat.java