apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  labels:
    app: hello-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-flask
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: flask-app
        image: 648798505204.dkr.ecr.ap-northeast-2.amazonaws.com/jenkins-ecr:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
spec:
  type: LoadBalancer
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80